# Deploy React app (inside ./webapp-firebase) to Firebase Hosting on merge to master

name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Recreate .env file from GitHub secrets
        working-directory: ./webapp-firebase
        run: |
          echo "Rebuilding .env file from GitHub secrets..."
          touch .env

          # Pull all secrets (including VITE_ ones)
          for var in $(printenv | grep -E '^(VITE_|REACT_|FIREBASE_|API_|APP_)'); do
            key=$(echo $var | cut -d= -f1)
            value=$(printenv $key)
            echo "$key=$value" >> .env
          done

          echo "✅ .env file created:"
          cat .env | grep -v PASSWORD || true  # avoid printing sensit
