name: Deploy to Firebase Hosting (nested project)

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./webapp-firebase

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Prepare Firebase service account JSON
        # This writes the secret into a JSON file inside the webapp-firebase folder
        # Make sure your secret contains the raw JSON content (not base64). See note below.
        run: |
          echo "$FIREBASE_SA" > ./sa.json
        env:
          FIREBASE_SA: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GENERATE_3S_KVB }}

      - name: Install firebase-tools
        run: |
          npm install -g firebase-tools@latest

      - name: Deploy to Firebase Hosting
        env:
          # point firebase-tools to the service account JSON so it can authenticate
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/webapp-firebase/sa.json
        run: |
          # make sure firebase.json is present in ./webapp-firebase/
          ls -la
          npx firebase deploy --only hosting --project generate-3s-kvb --non-interactive
