# Deploy React app (inside ./webapp-firebase) to Firebase Hosting on merge to master

name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env from GitHub Secrets
        working-directory: ./webapp-firebase
        run: |
          touch .env
          echo "Creating .env file from GitHub secrets..."
          for var in $(printenv | grep ^VITE_); do
            key=$(echo $var | cut -d= -f1)
            value=$(printenv $key)
            echo "$key=$value" >> .env
          done

      - name: Install dependencies and build
        working-directory: ./webapp-firebase
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GENERATOR_3SG_KVB }}
          channelId: live
          projectId: generator-3sg-kvb
          entryPoint: ./webapp-firebase
